### ISSUE TITLE
Text size is inconsistent and other visual feedback

### ISSUE THREAD

**Issue by juanruitina** [canonical/prompting-client#85]
In addition to the more urgent functional feedback (https://github.com/canonical/prompting-client/issues/82), some visual comments on the current implementation:

- [ ] All text in the prompt should have the same size, except the path. Body text seems to be the right one, but fields (radio buttons, checkboxes, inputs) are the ones that seem too big. This is what it looks like right now:

<img width="649" alt="Screenshot 2024-09-03 at 11 31 00" src="https://github.com/user-attachments/assets/edd12aab-4a19-4729-ab1d-ca464a2fc5c5">

It should look closer to this (ignore the icon):

![More options](https://github.com/user-attachments/assets/dfade04f-6331-4b42-ac96-eb2e38eaade0)

- [x] Can we show the input field under "Custom path" as nested, as per the design? A bit of an indent would be enough
- [x] Let's please also hide "Learn about path patterns" under "Custom path" until we figure out what information to provide there. 
- [x] Similarly, I see the info under "About this app" is incomplete, link doesn't seem to work either. Do we consider this to be in scope? If it doesn't work, it should be hidden.

**Comment by sminez** [comment]
The inconsistent text size issue looks to be an issue with [yaru.dart](https://github.com/ubuntu/yaru.dart) which @d-loose is raising an issue for. The other items listed here have all been addressed in the UI fixes merged this week so I'm going to close this one now.
