### ISSUE TITLE
Write permission prompt fails to action when an existing read permission is already granted

### ISSUE THREAD

**Issue by alexmurray** [canonical/prompting-client#91]
Whilst experimenting with the new prompting client, I noticed some weird behaviour when using the audacity snap - see the attached video for an overview as it is hard to explain, but essentially if a user has already granted read permission for a particular path, when a subsequent prompt arrives when the application then tries to write to that same path, there is no way to actually allow that to proceed - clicking the Allow button doesn't do anything. The only way to get this to work is to go into the security center and revoke the read rule and then when prompted to allow read access in the future, grant both read and write.
[Screencast From 2024-09-06 13-56-57.webm](https://github.com/user-attachments/assets/3c719b40-4699-4a65-a2ac-90478b5d93f7)

**Comment by alexmurray** [comment]
@sminez yes this is the same issue.

**Comment by sminez** [comment]
I'll close this issue in favour of that one then to keep things in one place 👍
